# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cf_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.NullBooleanField(choices=[(None, 'Ожидает проверки'), (True, 'Разрешено'), (False, 'Отклонено')], default=None, verbose_name='статус модерации')),
                ('approved_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='дата модерации')),
                ('process_status', models.CharField(blank=True, choices=[('', 'Ожидание'), ('CHECK', 'Отправлен на проверку'), ('APPLY', 'Применяется')], default='', max_length=8, verbose_name='Статус обработки модерации')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='', max_length=2048, verbose_name='название')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(default=None, null=True, upload_to='', verbose_name='большой блок')),
                ('small_logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='', verbose_name='маленький блок')),
                ('video', models.URLField(blank=True, default='', verbose_name='ссылка на youtube video')),
                ('short_description', models.TextField(default='', verbose_name='короткое описание')),
                ('description', models.TextField(default='', verbose_name='подробное описание')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='завершение проекта')),
                ('total_amount', models.BigIntegerField(default=0, help_text='Цель', verbose_name='общая сумма для сборов')),
                ('collected_amount', models.BigIntegerField(default=0, verbose_name='собранные средства')),
                ('articles_of_association', models.FileField(blank=True, default='', upload_to='', verbose_name='устав')),
                ('articles_of_association_approved', models.NullBooleanField(default=False, verbose_name='устав подтвержден')),
                ('extract_from_egrul', models.FileField(blank=True, default='', upload_to='', verbose_name='Выписка из ЮГРЮЛ')),
                ('extract_from_egrul_approved', models.NullBooleanField(default=False, verbose_name='выписка из ЮГРЮЛ подтверждена')),
                ('general_meeting_decision', models.FileField(blank=True, default='', upload_to='', verbose_name='решение общего собрания об утверждении проекта')),
                ('general_meeting_decision_approved', models.NullBooleanField(default=False, verbose_name='файл решения общего собрания подтвержден')),
                ('auditor_notes', models.TextField(blank=True, default='', max_length=1024, verbose_name='заметка аудитора')),
                ('auditor_approved', models.NullBooleanField(choices=[(None, 'Ожидает проверки'), (True, 'Разрешено'), (False, 'Отклонено')], default=None, verbose_name='подтвержден аудитором')),
                ('approved_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverts_granted_list', to=settings.AUTH_USER_MODEL, verbose_name='модератор')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_audits', to=settings.AUTH_USER_MODEL, verbose_name='аудитор')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
        migrations.CreateModel(
            name='AdvertEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=512, verbose_name='работа/материал')),
                ('amount', models.IntegerField(verbose_name='сумма в рубля')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='cf_adverts.Advert', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'смета проекта',
                'verbose_name_plural': 'сметы проектов',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=512, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категория',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('base_type', models.CharField(choices=[('CUSTOM', 'Ручное создание'), ('PROJECT_CREATED', 'Проект создан'), ('PROJECT_EDITED', 'Проект отредактирован'), ('USER_JOINED', 'Новый участник'), ('PERCENT_CHANGED', 'Достижение процентов цели'), ('PROJECT_DONE', 'Проект завершен'), ('PAYMENT_RECEIVED', 'Принят платеж'), ('RESOURCE_RECEIVED', 'Принят материал/ресурс')], max_length=64, verbose_name='тип события')),
                ('percent', models.IntegerField(verbose_name='процент сборов')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cf_adverts.Advert', verbose_name='объявление')),
            ],
            options={
                'verbose_name': 'событие объявления',
                'ordering': ['-created'],
                'verbose_name_plural': 'события объявлений',
            },
        ),
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='cf_adverts.Category', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='advert',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cf_core.Location', verbose_name='район'),
        ),
        migrations.AddField(
            model_name='advert',
            name='origin',
            field=models.OneToOneField(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='cf_adverts.Advert', verbose_name='оригинал'),
        ),
        migrations.AddField(
            model_name='advert',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='инициатор'),
        ),
        migrations.AddField(
            model_name='advert',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_core.Status', verbose_name='статус'),
        ),
        migrations.CreateModel(
            name='BannedAdvert',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name_plural': 'заблокированное объявление',
                'verbose_name': 'заблокированное объявление',
                'proxy': True,
            },
            bases=('cf_adverts.advert',),
        ),
        migrations.CreateModel(
            name='DraftAdvert',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name_plural': 'черновики объявлений',
                'verbose_name': 'черновик объявления',
                'proxy': True,
            },
            bases=('cf_adverts.advert',),
        ),
        migrations.CreateModel(
            name='NewAdvert',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name_plural': 'новые объявления',
                'verbose_name': 'новое объявление',
                'proxy': True,
            },
            bases=('cf_adverts.advert',),
        ),
        migrations.CreateModel(
            name='PublishedAdvert',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name_plural': 'объявления',
                'verbose_name': 'объявление',
                'proxy': True,
            },
            bases=('cf_adverts.advert',),
        ),
    ]
