# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cf_adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name': 'advert', 'verbose_name_plural': 'adverts'},
        ),
        migrations.AlterModelOptions(
            name='advertestimate',
            options={'verbose_name': 'advert estimate', 'verbose_name_plural': 'advert estimates'},
        ),
        migrations.AlterModelOptions(
            name='bannedadvert',
            options={'verbose_name': 'blocked advert', 'verbose_name_plural': 'blocked adverts'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='draftadvert',
            options={'verbose_name': 'draft advert', 'verbose_name_plural': 'draft adverts'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created'], 'verbose_name': 'advert event', 'verbose_name_plural': 'advert events'},
        ),
        migrations.AlterModelOptions(
            name='newadvert',
            options={'verbose_name': 'new advert', 'verbose_name_plural': 'new adverts'},
        ),
        migrations.AlterModelOptions(
            name='publishedadvert',
            options={'verbose_name': 'published advert', 'verbose_name_plural': 'published adverts'},
        ),
        migrations.AlterField(
            model_name='advert',
            name='articles_of_association',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='articles of association'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='articles_of_association_approved',
            field=models.NullBooleanField(default=False, verbose_name='articles of association approved'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_audits', to=settings.AUTH_USER_MODEL, verbose_name='auditor'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='auditor_approved',
            field=models.NullBooleanField(choices=[(None, 'Ожидает проверки'), (True, 'Разрешено'), (False, 'Отклонено')], default=None, verbose_name='approved by auditor'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='auditor_notes',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='auditor notes'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='cf_adverts.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='collected_amount',
            field=models.BigIntegerField(default=0, verbose_name='collected amount'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='ended_at',
            field=models.DateField(blank=True, null=True, verbose_name='ended at'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='extract_from_egrul',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='extract from egrul'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='extract_from_egrul_approved',
            field=models.NullBooleanField(default=False, verbose_name='extract from the Unified State Register of Legal Entities is confirmed'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='general_meeting_decision',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='the decision of the general meeting on the approval of the project'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='general_meeting_decision_approved',
            field=models.NullBooleanField(default=False, verbose_name='the file of the decision of the general meeting is confirmed'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cf_core.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(default=None, null=True, upload_to='', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='origin',
            field=models.OneToOneField(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='cf_adverts.Advert', verbose_name='original'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='process_status',
            field=models.CharField(blank=True, choices=[('', 'Ожидание'), ('CHECK', 'Отправлен на проверку'), ('APPLY', 'Применяется')], default='', max_length=8, verbose_name='статус обработки модерации'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='short_description',
            field=models.TextField(default='', verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='small_logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='', verbose_name='small logo'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_core.Status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(default='', max_length=2048, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='total_amount',
            field=models.BigIntegerField(default=0, help_text='goal', verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='video',
            field=models.URLField(blank=True, default='', verbose_name='youtube video link'),
        ),
        migrations.AlterField(
            model_name='advertestimate',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='cf_adverts.Advert', verbose_name='advert'),
        ),
        migrations.AlterField(
            model_name='advertestimate',
            name='amount',
            field=models.IntegerField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='advertestimate',
            name='title',
            field=models.CharField(max_length=512, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=512, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cf_adverts.Advert', verbose_name='advert'),
        ),
        migrations.AlterField(
            model_name='event',
            name='base_type',
            field=models.CharField(choices=[('CUSTOM', 'custom event'), ('PROJECT_CREATED', 'advert created'), ('PROJECT_EDITED', 'advert changed'), ('USER_JOINED', 'user joined'), ('PERCENT_CHANGED', 'percent changed'), ('PROJECT_DONE', 'advert done'), ('PAYMENT_RECEIVED', 'payment received'), ('RESOURCE_RECEIVED', 'resource received')], max_length=64, verbose_name='base type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='percent',
            field=models.IntegerField(verbose_name='percent'),
        ),
    ]
